-- Run in the existing clinic-attendance Supabase project.
-- Separate records keep a lesson check-in from satisfying a clinic check-in.
begin;
create table if not exists public.class_attendance (
  id bigint generated by default as identity primary key,
  student_id text not null check (length(trim(student_id)) between 1 and 100),
  student_name text not null check (length(trim(student_name)) between 1 and 100),
  class_id text not null check (class_id in ('hanbaek_wed_1800','hanbaek_sat_1030','hanbaek_sat_1430','chidong_sat_1800','hanbaek_sun_1030','chidong_sun_1430')),
  lesson_date date not null,
  checked_in_at timestamptz not null default now(),
  cancelled_at timestamptz,
  unique (student_id,class_id,lesson_date),
  check (lesson_date=(checked_in_at at time zone 'Asia/Seoul')::date),
  check (extract(dow from lesson_date)=case when class_id='hanbaek_wed_1800' then 3 when class_id like '%_sat_%' then 6 else 0 end)
);
alter table public.class_attendance enable row level security;
-- Use the same read audience as the existing attendance viewer. All writes use RPCs.
revoke select on public.class_attendance from public,anon,authenticated;
revoke insert,update,delete on public.class_attendance from anon,authenticated;
drop policy if exists class_attendance_read on public.class_attendance;

create or replace function public.check_in_class(p_student_id text,p_student_name text,p_class_id text,p_checked_in_at timestamptz default now())
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result public.class_attendance; lesson_day date;
begin
  if p_checked_in_at is null or p_checked_in_at>now()+interval '5 minutes' or p_checked_in_at<now()-interval '7 days' then raise exception 'invalid check-in time'; end if;
  lesson_day:=(p_checked_in_at at time zone 'Asia/Seoul')::date;
  insert into public.class_attendance(student_id,student_name,class_id,lesson_date,checked_in_at)
  values(p_student_id,p_student_name,p_class_id,lesson_day,p_checked_in_at)
  on conflict(student_id,class_id,lesson_date) do nothing;
  select * into result from public.class_attendance where student_id=p_student_id and class_id=p_class_id and lesson_date=lesson_day;
  if result.cancelled_at is not null then raise exception '교사가 취소한 출석입니다. 선생님에게 확인해 주세요.'; end if;
  return jsonb_build_object('id',result.id,'checked_in_at',p_checked_in_at);
end; $$;

create or replace function public.teacher_edit_class_attendance(p_pin text,p_action text,p_student_id text,p_student_name text,p_class_id text,p_lesson_date date)
returns jsonb language plpgsql security definer set search_path=public,private,extensions,pg_temp as $$
declare saved_hash text; result public.class_attendance; at_time timestamptz; start_time text;
begin
  select pin_hash into saved_hash from private.clinic_teacher_settings where singleton=true;
  if saved_hash is null or p_pin is null or extensions.crypt(p_pin,saved_hash) is distinct from saved_hash then raise exception 'invalid teacher pin' using errcode='28000'; end if;
  if p_lesson_date is null or p_lesson_date>(now() at time zone 'Asia/Seoul')::date then raise exception '미래 날짜는 출석 처리할 수 없습니다.'; end if;
  if p_action='present' then
    start_time:=case when p_class_id like '%_1030' then '10:30' when p_class_id like '%_1430' then '14:30' else '18:00' end;
    at_time:=case when p_lesson_date=(now() at time zone 'Asia/Seoul')::date then now() else (p_lesson_date::text||' '||start_time)::timestamp at time zone 'Asia/Seoul' end;
    insert into public.class_attendance(student_id,student_name,class_id,lesson_date,checked_in_at)
    values(p_student_id,p_student_name,p_class_id,p_lesson_date,at_time)
    on conflict(student_id,class_id,lesson_date) do update set cancelled_at=null,checked_in_at=excluded.checked_in_at
    returning * into result;
  elsif p_action='cancel' then
    update public.class_attendance set cancelled_at=now() where student_id=p_student_id and class_id=p_class_id and lesson_date=p_lesson_date returning * into result;
  else raise exception 'invalid action'; end if;
  return jsonb_build_object('ok',true,'record',to_jsonb(result));
end; $$;
revoke all on function public.check_in_class(text,text,text,timestamptz) from public;
revoke all on function public.teacher_edit_class_attendance(text,text,text,text,text,date) from public;
grant execute on function public.check_in_class(text,text,text,timestamptz) to anon,authenticated;
grant execute on function public.teacher_edit_class_attendance(text,text,text,text,text,date) to anon,authenticated;

create or replace function public.teacher_read_attendance(p_pin text,p_kind text,p_start timestamptz default null,p_end timestamptz default null)
returns jsonb language plpgsql security definer set search_path=public,private,extensions,pg_temp as $$
declare saved_hash text; records jsonb;
begin
 select pin_hash into saved_hash from private.clinic_teacher_settings where singleton=true;
 if saved_hash is null or p_pin is null or extensions.crypt(p_pin,saved_hash) is distinct from saved_hash then raise exception 'invalid teacher pin' using errcode='28000'; end if;
 if p_kind='class' then
  select coalesce(jsonb_agg(t),'[]'::jsonb) into records from (select * from public.class_attendance where cancelled_at is null and (p_start is null or checked_in_at>=p_start) and (p_end is null or checked_in_at<p_end) order by checked_in_at desc) t;
 elsif p_kind='clinic' then
  select coalesce(jsonb_agg(t),'[]'::jsonb) into records from (select * from public.clinic_attendance where (p_start is null or checked_in_at>=p_start) and (p_end is null or checked_in_at<p_end) order by checked_in_at desc) t;
 else raise exception 'invalid attendance kind'; end if;
 return records;
end; $$;
revoke all on function public.teacher_read_attendance(text,text,timestamptz,timestamptz) from public;
grant execute on function public.teacher_read_attendance(text,text,timestamptz,timestamptz) to anon,authenticated;
revoke select on public.clinic_attendance from public,anon,authenticated;

notify pgrst,'reload schema';
commit;

